<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace melkov\models\base;

use Yii;

/**
 * This is the base-model class for table "geo_ip".
 *
 * @property integer $id
 * @property integer $city_id
 * @property string $start
 * @property string $end
 *
 * @property \melkov\models\GeoCity $city
 * @property string $aliasModel
 */
abstract class GeoIp extends \melkov\db\ActiveRecord 
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'geo_ip';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['city_id'], 'required'],
            [['city_id'], 'integer'],
            [['start', 'end'], 'string'],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => GeoCity::className(), 'targetAttribute' => ['city_id' => 'id']],
            [['start', 'end'], 'trim']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('label', 'ID'),
            'city_id' => Yii::t('label', 'City ID'),
            'start' => Yii::t('label', 'Start'),
            'end' => Yii::t('label', 'End'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity()
    {
        return $this->hasOne(\melkov\models\GeoCity::className(), ['id' => 'city_id']);
    }


    
    /**
     * @inheritdoc
     * @return \melkov\models\query\GeoIpQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \melkov\models\query\GeoIpQuery(get_called_class());
    }


}
