<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace melkov\components\models\base;

use Yii;

/**
 * This is the base-model class for table "language_translate".
 *
 * @property integer $id
 * @property string $language
 * @property string $translation
 *
 * @property \common\models\LanguageSource $id0
 * @property string $aliasModel
 */
abstract class LanguageTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'language_translate';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'language'], 'required'],
            [['id'], 'integer'],
            [['translation'], 'string'],
            [['language'], 'string', 'max' => 16],
            [['id'], 'exist', 'skipOnError' => true, 'targetClass' => LanguageSource::className(), 'targetAttribute' => ['id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'language' => Yii::t('translate', 'Language'),
            'translation' => Yii::t('translate', 'Translation'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getId0()
    {
        return $this->hasOne(\melkov\components\models\LanguageSource::className(), ['id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \melkov\components\models\query\LanguageTranslateQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \melkov\components\models\query\LanguageTranslateQuery(get_called_class());
    }


}
