<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace melkov\components\models\base;

use Yii;

/**
 * This is the base-model class for table "language_source".
 *
 * @property integer $id
 * @property string $category
 * @property string $message
 *
 * @property \common\models\LanguageTranslate[] $languageTranslates
 * @property string $aliasModel
 */
abstract class LanguageSource extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'language_source';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message'], 'string'],
            [['category'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'category' => Yii::t('translate', 'Category'),
            'message' => Yii::t('translate', 'Message'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLanguageTranslates()
    {
        return $this->hasMany(\melkov\components\models\LanguageTranslate::className(), ['id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \melkov\components\models\query\LanguageSourceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \melkov\components\models\query\LanguageSourceQuery(get_called_class());
    }


}
